//! What a case still holds after it has been closed and opened again.
//!
//! Every other test in this workspace works inside one process with one
//! in-memory `CaseMasterKey`, generated by the test and handed to both the write
//! and the read. That is a fixture, not a case. A real investigation is opened
//! on Monday, closed, and opened again on Thursday, and the only thing that
//! survives in between is the case directory and something the analyst can
//! remember or has written down.
//!
//! This file draws the line at process exit deliberately: everything before the
//! reopen is dropped, and only the passphrase crosses.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::path::PathBuf;
use std::sync::atomic::{AtomicU32, Ordering};

use kokin_blob::BlobStore;
use kokin_ingest::{ingest_file, IngestContext};

static COUNTER: AtomicU32 = AtomicU32::new(0);

const PASSPHRASE: &str = "correct horse battery staple";
const CONTENT: &[u8] = b"<html><title>Acme Holdings</title><body>QX-7741</body></html>";

fn case_dir(name: &str) -> PathBuf {
    let n = COUNTER.fetch_add(1, Ordering::Relaxed);
    let mut dir = std::env::temp_dir();
    dir.push(format!("kokin-reopen-{name}-{}-{n}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    dir
}

/// The test that had no way to pass before this increment.
///
/// `open_case` returned a connection and some paths and dropped the case master
/// key on the floor. Blob filenames are keyed with that key (`storage_name`), so
/// a reopened case could not locate its own evidence, never mind decrypt it —
/// and no test noticed, because every test generated a fresh key and used it for
/// both halves of its own round trip.
///
/// What makes this the failure worth pinning: the database reopens perfectly.
/// The artifact row, its hash, its lineage and its observations are all there.
/// Only the bytes are unreachable, so the case looks intact right up to the
/// moment someone asks to see the document.
#[test]
fn a_case_can_still_read_its_evidence_after_being_closed_and_opened() {
    let dir = case_dir("evidence");
    let file = dir.join("page.html");

    let (artifact_id, content_hash) = {
        let (
            kokin_store::OpenCase {
                mut conn,
                paths,
                cmk,
            },
            _recovery,
        ) = kokin_store::create_case(dir.join("case.kokincase"), "case-reopen", PASSPHRASE)
            .unwrap();
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(&file, CONTENT).unwrap();

        let blobs = BlobStore::new(paths.blobs());
        let outcome = ingest_file(
            &mut conn,
            &blobs,
            &cmk,
            &file,
            &IngestContext {
                connector: "file_import",
                job_id: "job-reopen",
            },
        )
        .unwrap();

        let hash: String = conn
            .query_row(
                "SELECT content_hash FROM artifact WHERE id = ?1",
                [&outcome.artifact_id],
                |r| r.get(0),
            )
            .unwrap();
        (outcome.artifact_id, hash)
    };
    // Everything above is dropped here: the connection, the key, the blob store.
    // Only `dir` and PASSPHRASE cross this line, which is all a returning
    // analyst has.

    let reopened = kokin_store::open_case(dir.join("case.kokincase"), PASSPHRASE).unwrap();
    let blobs = BlobStore::new(reopened.paths.blobs());

    let stored: String = reopened
        .conn
        .query_row(
            "SELECT content_hash FROM artifact WHERE id = ?1",
            [&artifact_id],
            |r| r.get(0),
        )
        .unwrap();
    assert_eq!(stored, content_hash, "the case forgot its own artifact");

    assert!(
        blobs.contains(&content_hash, &reopened.cmk),
        "a reopened case cannot find the blob it ingested"
    );

    // The whole path an application takes: hash out of the database, key out of
    // the database, bytes off the disk. Nothing here was carried over from the
    // block above.
    let access = kokin_store::blob_access(&reopened.conn, &content_hash).unwrap();
    let kokin_store::BlobAccess::Readable(reference) = access else {
        panic!("a reopened case reported its own evidence as unreadable: {access:?}");
    };
    let bytes = blobs
        .get(&reference, &reopened.cmk)
        .expect("a reopened case cannot decrypt the blob it ingested");
    assert_eq!(bytes, CONTENT, "the bytes came back changed");

    let _ = std::fs::remove_dir_all(&dir);
}

/// The wrong passphrase must fail at the key, not at the blob.
///
/// Worth separating because the two failures look identical from the UI - both
/// are "cannot read this case" - and only one of them means the analyst typed
/// the wrong thing.
#[test]
fn the_wrong_passphrase_never_gets_as_far_as_the_blobs() {
    let dir = case_dir("wrongpass");
    std::fs::create_dir_all(&dir).unwrap();
    let file = dir.join("page.html");
    std::fs::write(&file, CONTENT).unwrap();

    {
        let (
            kokin_store::OpenCase {
                mut conn,
                paths,
                cmk,
            },
            _recovery,
        ) = kokin_store::create_case(dir.join("case.kokincase"), "case-wrong", PASSPHRASE).unwrap();
        let blobs = BlobStore::new(paths.blobs());
        ingest_file(
            &mut conn,
            &blobs,
            &cmk,
            &file,
            &IngestContext {
                connector: "file_import",
                job_id: "job-wrong",
            },
        )
        .unwrap();
    }

    assert!(kokin_store::open_case(dir.join("case.kokincase"), "not it").is_err());

    let _ = std::fs::remove_dir_all(&dir);
}

/// The recovery key has to reach the bytes too, not just the database.
///
/// It unwraps the same CMK by a different route, so this could not fail on its
/// own — but it is the route taken when a passphrase is lost, which is to say
/// the route nobody exercises until the day it has to work.
#[test]
fn a_recovery_key_reaches_the_evidence_the_passphrase_would_have() {
    let dir = case_dir("recovery");
    std::fs::create_dir_all(&dir).unwrap();
    let file = dir.join("page.html");
    std::fs::write(&file, CONTENT).unwrap();

    let (recovery, content_hash) = {
        let (
            kokin_store::OpenCase {
                mut conn,
                paths,
                cmk,
            },
            recovery,
        ) = kokin_store::create_case(dir.join("case.kokincase"), "case-recovery", PASSPHRASE)
            .unwrap();
        let blobs = BlobStore::new(paths.blobs());
        let outcome = ingest_file(
            &mut conn,
            &blobs,
            &cmk,
            &file,
            &IngestContext {
                connector: "file_import",
                job_id: "job-recovery",
            },
        )
        .unwrap();
        let hash: String = conn
            .query_row(
                "SELECT content_hash FROM artifact WHERE id = ?1",
                [&outcome.artifact_id],
                |r| r.get(0),
            )
            .unwrap();
        (recovery, hash)
    };
    // The recovery key is the one thing that is *supposed* to cross this line,
    // because it is kept outside the case by definition.

    let reopened =
        kokin_store::open_case_with_recovery_key(dir.join("case.kokincase"), &recovery).unwrap();
    let blobs = BlobStore::new(reopened.paths.blobs());

    let kokin_store::BlobAccess::Readable(reference) =
        kokin_store::blob_access(&reopened.conn, &content_hash).unwrap()
    else {
        panic!("a recovered case could not reach its evidence");
    };
    assert_eq!(blobs.get(&reference, &reopened.cmk).unwrap(), CONTENT);

    let _ = std::fs::remove_dir_all(&dir);
}

/// Destroyed on purpose must not read as damaged.
///
/// Both states are "you cannot see this document", and the difference between
/// them is the difference between the product working and the case being
/// broken. Collapsing them would have an analyst chasing corruption that is
/// actually their own retention policy.
#[test]
fn evidence_destroyed_on_purpose_does_not_read_as_a_broken_case() {
    let dir = case_dir("shredded");
    std::fs::create_dir_all(&dir).unwrap();
    let file = dir.join("page.html");
    std::fs::write(&file, CONTENT).unwrap();

    let content_hash = {
        let (
            kokin_store::OpenCase {
                mut conn,
                paths,
                cmk,
            },
            _recovery,
        ) = kokin_store::create_case(dir.join("case.kokincase"), "case-shred", PASSPHRASE).unwrap();
        let blobs = BlobStore::new(paths.blobs());
        let outcome = ingest_file(
            &mut conn,
            &blobs,
            &cmk,
            &file,
            &IngestContext {
                connector: "file_import",
                job_id: "job-shred",
            },
        )
        .unwrap();
        let hash: String = conn
            .query_row(
                "SELECT content_hash FROM artifact WHERE id = ?1",
                [&outcome.artifact_id],
                |r| r.get(0),
            )
            .unwrap();

        // The transition the append-only trigger exists to permit.
        conn.execute(
            "UPDATE blob
                SET wrapped_key = NULL, wrapped_nonce = NULL,
                    shredded_utc = '2026-08-13T00:00:00Z'
              WHERE content_hash = ?1",
            [&hash],
        )
        .unwrap();
        hash
    };

    let reopened = kokin_store::open_case(dir.join("case.kokincase"), PASSPHRASE).unwrap();

    // The provenance is still there. That is the point of shredding: the record
    // that this evidence was collected outlives the evidence.
    let artifacts: i64 = reopened
        .conn
        .query_row(
            "SELECT count(*) FROM artifact WHERE content_hash = ?1",
            [&content_hash],
            |r| r.get(0),
        )
        .unwrap();
    assert_eq!(artifacts, 1, "shredding took the provenance with it");

    match kokin_store::blob_access(&reopened.conn, &content_hash).unwrap() {
        kokin_store::BlobAccess::Shredded { shredded_utc } => {
            assert_eq!(shredded_utc.as_deref(), Some("2026-08-13T00:00:00Z"));
        }
        other => panic!("shredded evidence reported as {other:?}"),
    }

    // And a hash this case never held is a third answer, not the same one.
    assert_eq!(
        kokin_store::blob_access(&reopened.conn, &"0".repeat(64)).unwrap(),
        kokin_store::BlobAccess::Unrecorded
    );

    let _ = std::fs::remove_dir_all(&dir);
}
